# conda env create -f environment.yml
# conda env update -f environment.yml

name: activity_tracker
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python>=3.12
  - pandas
  - matplotlib
  - numpy
  - ipykernel
  - pip:
      - openpyxl
      - plotly
      - python-dotenv
      - pyodbc
      - pyyaml
      - seaborn
      - -e .
